apiVersion: apps/v1
kind: Deployment
metadata:
  name: everest-demo
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: EVEREST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: everest-demo-secret
                  key: username
            - name: EVEREST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: everest-demo-secret
                  key: password
