apiVersion: v1
kind: Service
metadata:
  name: everest-demo
  namespace: everest-dev
  labels:
    app: everest-demo
    project: project-everest
spec:
  type: ClusterIP
  selector:
    app: everest-demo
  ports:
    - name: http
      port: 80
      targetPort: http