apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: everest-demo-secret
  namespace: everest-dev
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: everest-demo-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: everest/dev/demo
        property: username

    - secretKey: password
      remoteRef:
        key: everest/dev/demo
        property: password
